site_name: DS223 Group Project
site_url: https://hovhannisyan91.github.io/DS223_Group_Project/
repo_url: https://github.com/hovhannisyan91/DS223_Group_Project

docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - Home: index.md
  - Demo: demo.md
  - ETL: etl.md
  - API: api.md
  - APP: app.md
  - API models: api_models.md
  - Tutorial: https://hovhannisyan91.github.io/DS223_Group_Project/tutorial/

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
